### ISSUE TITLE
how to get started ?

### ISSUE THREAD

**Issue by aawaheed** [GenesysSource/Framework-for-Core#1]
I am trying to run the application but I am getting **Database: [✘] Not connected** 
I have changed the _DefaultConnection_ to match my local connection string. 

Steps I followed:

- Downloaded the vsix file from [marketplace](https://marketplace.visualstudio.com/items?itemName=GenesysSource.GenesysFrameworkQuick-StartforCore)

- Installed the extension 

- Created a new project with Genesys-Quick-Start for Core

- Changed the DefaultConnection

- Ran the Publish in Framework.Database

- Started the application Framework.WebApp.Core

Seems like Readme and guides are more towards pre-.net core versions. 
any help?

**Comment by goodtocode** [comment]
Hi @aawaheed, will be glad to help. And thank you for being so thorough in your description. Mind trying a few things to see if we can connect successfully?

Some likely causes:
1. Please verify the new connection string in \App_Data\ConnectionStrings.{Environment}.json. 
- The environment-specific .json hold the actual values used at runtime.
2. Please use SQL Server or SQL Express if possible.
- LocalDB databases (direct .mdf files) are not supported in the current release
3. Does the default connection string work? 
- This is a sandbox database used to troubleshoot connection issues.
- Found in: \App_Data\ConnectionStrings.{Environment}.json
4. Please verify connection string in SQL Server Management Studio or ODBC connection wizard.
5. Here is the framework EF code, which contains the raw data access code: 

My apologies for the docs being out of date. We recently added .NET Core support and maintained .NET Framework support, via the .Shared projects…and docs are the last to know.

Please let me know if these suggestions were able to help.

Hope to speak soon,
Robert

**Comment by aawaheed** [comment]
Thanks @goodtocode. I got it working. It was my bad as after close inspection I found out that in data source I was putting (localhost) [not sure why 😮]. I am using SQL Server. I have another issue which I am open in a bit.
