### ISSUE TITLE
Sequence to run the application

### ISSUE THREAD

**Issue by aawaheed** [GenesysSource/Framework-for-Core#2]
As per the documentation in [MVC](https://github.com/GenesysSource/Framework-for-MVC), we are required to run WebService project as well. When I do the same for Framwork-for-core, I get 
**"Unable to connect to web server "IIS Express"**
I am using VS 2017 v15.8.4 with .Net Core 2.1

**Comment by goodtocode** [comment]
Hi @aawaheed, Thank you for the concise report, very kind. I reproduced the same issue, and this is a bug. The SSL port on Framework.WebApp.Core and Framework.WebServices.Core is the same, causing the error: "Unable to connect to web server "IIS Express".

To workaround this issue:
1. Open/Edit Framework.WebApp.Core\Properties\launchSettings.json 
2. Change from: "sslPort": 44337 
– to: "sslPort": 44303
3. Change from: "applicationUrl": "https://localhost:44337;http://localhost:30003"
- to: "applicationUrl": "https://localhost:44303;http://localhost:30003"

It will work. Also, Framework.WebServices is not required to run/debug Framework.WebApp. They are peers and both depend on only the SQL database, not each other.

I will 1. Update the documentation and 2. Change the SSL port, and submit the fix to GitHub and to marketplace.visualstudio.com. 

Thanks again for the great report!
Rober

**Comment by goodtocode** [comment]
Hi @aawaheed, Was able to make the change to the GitHub repo, and the VSIX/Visual Studio Marketplace version will be updated when the DevOps pipeline pushes sprint 2018.10. Also was able to make a correction to the existing documentation in hopes of being clear of which projects to run.

Please let me know if the fix works for you, and will be glad to help with questions and concerns that may pop up.

Thank you again for your help!
Robert

**Comment by aawaheed** [comment]
Hi @goodtocode . I can confirm that the fix did work and I was able to run the application.
Much appreciated your help.
